name: .zip Pack Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag ou version de la release (ex: v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create ZIP archive
      run: |
        mkdir release-folder
        cp -r assets pack.mcmeta pack.png readme.txt release-folder/
        cd release-folder
        zip -r ../release.zip ./*
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        files: release.zip
        prerelease: ${{ github.event.inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
