name: .zip pack release


on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Nom de la release (ex: LMC v1.0.3)'
        required: true
      tag_name:
        description: 'Nom du tag (créé automatiquement, ex: v1.0.3)'
        required: true
      prerelease:
        description: 'Est-ce une pre-release ?'
        required: false
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create ZIP archive
      run: |
        mkdir release-folder
        cp -r assets pack.mcmeta pack.png readme.txt release-folder/
        cd release-folder
        zip -r "../LMC-${{ github.event.inputs.tag_name }}.zip" ./*
        cd ..

    - name: Create GitHub Release (without local git tag)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: LMC-${{ github.event.inputs.tag_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
