name: .zip pack release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Nom du tag (ex: v1.0.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with tags
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Important pour récupérer tous les commits et tags

    - name: Setup authenticated remote
      run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Check if tag exists and create it
      run: |
        echo "Vérification du tag ${{ github.event.inputs.tag_name }}..."
        if git ls-remote --tags origin | grep -q "refs/tags/${{ github.event.inputs.tag_name }}$"; then
          echo "❌ Le tag existe déjà. Abandon."
          exit 1
        fi

        echo "Création du tag ${{ github.event.inputs.tag_name }}..."
        git tag ${{ github.event.inputs.tag_name }}
        git push origin ${{ github.event.inputs.tag_name }}

    - name: Create ZIP archive
      run: |
        mkdir release-folder
        cp -r assets pack.mcmeta pack.png readme.txt release-folder/
        cd release-folder
        zip -r ../release.zip ./*
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        files: release.zip
        prerelease: ${{ github.event.inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
